### ISSUE TITLE
Is there any trained  model （cifar10.rbx）?

### ISSUE THREAD

**Issue by augushong** [RubixML/CIFAR-10#1]
The training model takes too much time. Is there a model that has completed the training?

**Comment by andrewdalpino** [comment]
We currently do not provide a trained model along with the tutorials but it's something I would consider doing in the future. Are you using the Tensor extension?

https://github.com/RubixML/Tensor

**Comment by augushong** [comment]
Thank you for your reply.
I don't need it anymore. I've trained a model, but I found that its accuracy is only about 80%.
I'm very interested in AI, but I'm just a traditional PHP developer and don't know much about AI. I'm continuing to study.
Here is my training model. See if it works.
I'm planning to do a demo project with a complete model. Maybe I'll trouble you a lot in the future.

[cifar10.zip](https://github.com/RubixML/CIFAR-10/files/8477506/cifar10.zip)
